### ISSUE TITLE
API v1 - getNetworkEvents looping on 'endingBefore' date set to 1970-01-01

### ISSUE THREAD

**Issue by Philippe-Ragon** [meraki/dashboard-api-python#116]
I am calling networks.getNetworkEvents() with total_pages set to -1 in order to retrieve all the events or a specific list of events of a network.

Log of Execution (in attachment) is showing that there is an infinite loop of get request with 'endingBefore' set to '1970-01-01' (starting with page 610 in the log).

I think the issue comes from 'session.get_pages()' which is looping to retrieve the requested number of pages with:

while total_pages != 1:
       'retrieve next page and append response to results'
        total_pages -= 1

With total_pages set to -1 this is obviously looping.

Remark : this is an issue for all the caller of 'session.get_pages()' not just networks.getNetworkEvents()

I was expecting that the library would stop trying to get additional events when an 'end of event log file' condition would be met.
If this is not possible, I suggest a test of  'endingBefore' obtained from the previous page.
If the date is one year older than current date, then one leave the loop.

[meraki_api__log__2020-09-04_12-16-08.log](https://github.com/meraki/dashboard-api-python/files/5174327/meraki_api__log__2020-09-04_12-16-08.log)

**Comment by shiyuechengineer** [comment]
Hi Philippe, as [pagination](https://developer.cisco.com/meraki/api-v1/#!pagination) is currently implemented, there is no _next_ or _prev_ link when an endpoint reaches the end of data. With the event log API endpoint, however, you can keep requesting more events just like you can keep clicking on the "newer"/"older" links on dashboard UI's _Network-wide > Event log_ page, and both of those links are returned, which results in an issue when you try to retrieve "all" pages here.

I've asked your SE to work with you a bit more to get more data on your exact use case, so that this logic can be modified accordingly. Thanks.

**Comment by shiyuechengineer** [comment]
Hi Philippe, thanks for your feedback, and your request was implemented just now in version 1.1.0b2. You can query the events for a network since a specified date with the following:
`events = dashboard.networks.getNetworkEvents(NET_ID, total_pages='all', direction='next', productType='appliance', perPage=1000, endingBefore='2020-06-01T00:00:00’)`

**Comment by Philippe-Ragon** [comment]
Hi Shiyue,

Thank you for the quick fix.
I have tested 1.1.0b2 and I have a few remarks.

Remark1 :
I confirm that a call with endingBefore=<date> & direction=’next’ is providing results from <date> to current time.
Logs are showing calls for successive page with keyword ‘startingAfter’ which is consistent with retrieved data.
This was confusing me to use a keyword containing stating ‘before date’ and retrieving data more recent than date.
So I tried a call with startingAfter=<date> & direction =’next’.
‘startingAfter’ is also working and providing the same results, and it is not confusing (my point of view)

Remark2:
endingBefore=<date>  (or  startingAfter=’date’) direction=’next’ are providing events in semi ordered manner (refer to attached Excel file).
For example if date is set to Jul 1, then results are :

  *   Jul 7 to Jul 1
  *   Jul 12 to Jul 7
  *   Jul 19 to 12
  *   …
It would be nice to have events with date either in ascending or descending order.

Remark3:
The quick fix allows to retrieve data from ‘date’ to current time.
It would be great to be able to retrive events between ‘date1’ and ‘date2’ i.e. ‘date2’ not necessarily set to current time.

Again thanks for the quick fix.

Philippe Ragon
+33 611 700 152

De : Shiyue Cheng <notifications@github.com>
Envoyé : mercredi 16 septembre 2020 20:50
À : meraki/dashboard-api-python <dashboard-api-python@noreply.github.com>
Cc : Philippe RAGON <philippe.ragon.ext@louisvuitton.com>; Author <author@noreply.github.com>
Objet : Re: [meraki/dashboard-api-python] API v1 - getNetworkEvents looping on 'endingBefore' date set to 1970-01-01 (#116)

________________________________
WARNING: This is an external email. Shall you have any doubt, report any suspicious e-mail by clicking on the "Report suspicious e-mail" button in Outlook.
________________________________


Hi Philippe, thanks for your feedback, and your request was implemented just now in version 1.1.0b2. You can query the events for a network since a specified date with the following:
events = dashboard.networks.getNetworkEvents(NET_ID, total_pages='all', direction='next', productType='appliance', perPage=1000, endingBefore='2020-06-01T00:00:00’)
