### ISSUE TITLE
Passing RADIUS secret in radiusServers kwarg for updateNetworkWirelessSsid

### ISSUE THREAD

**Issue by z3roCoo1** [meraki/dashboard-api-python#149]
So I figured this out but only after being directed to a reddit post from Google. Should be;

```
dashboard.wireless.updateNetworkWirelessSsid(netw, '0', 
    name = 'someSSID',
    enabled = True,
    authMode = '8021x-radius',
    wpaEncryptionMode = 'WPA2 only',
    radiusServers = [{'host': '172.16.1.1', 'port': 1812, 'secret': RADIUSsecret}, {'host': '172.16.1.2', 'port': 1812, 'secret': RADIUSsecret}]
```

My usual method of discovery is running the corresponding get first, but the secret is by design I guess not returned. So my issue is where _should_ I have discovered this in the official docs, rather than resorting to my feeble Google Fu?

Could this be made clearer in the doc string in the code? Or am I missing something else?

**Comment by TKIPisalegacycipher** [comment]
Hi @z3roCoo1, yes, this could potentially either be clearer in the docstrings in the spec, or via the interactive documentation site.  If you haven't already, I suggest making a wish (via Help > API Docs in dashboard) for the same so that this is tracked in the right place.

In any case, this is an issue with the API documentation, rather than the SDK, so I will close this issue. Hopefully this helps regardless.
