### ISSUE TITLE
SM Wipe Device API Issue

### ISSUE THREAD

**Issue by schultbr** [meraki/dashboard-api-python#20]
Upfront Context Disclosure: I lack context on how to determine if the API changed or if this "wrapper" has it wrong, so full disclosure there. As far as I understood, all API endpoints were to be backwards compatible, but maybe the API we have access to isn't the same as the version this library targets.

It seems there's a bit of a mismatch around the API for wiping devices and the function enclosed in this wrapper to invoke that endpoint. The specific endpoint is documented here: https://api.meraki.com/api_docs#wipe-a-device

Looking at the url, it targets a specific device. Comparing to the python variant, it tries to invoke a plural variant (devices instead of device - so https://api.meraki.com/api/v0/networks/[network_id]/sm/devices/wipe rather than the documented endpoint of https://api.meraki.com/api/v0/networks/[network_id]/sm/device/wipe) which takes lists of params rather than a single param (eg. 'ids' rather than 'id'). This is a fairly easy change, but again, I cannot tell if it _supposed_ to be plural or not.

**Comment by pocc** [comment]
The only way to tell is to test. device**s** fails on curl/this script where device succeeds.

**Curl error**: `The page you are looking for may have been moved or does not exist.` + an HTML webpage payload
**dashboard-api-python error**: `HTTP Status Code: 404 - No returned data`

Beyond this function failing due to an incorrect API call, I can't see how it can possibly work with 5 expected parameters with no differentiation. I.e. how is the function to tell which of [wifimacs, ids, serials, scope, pin] the user actually passed in?
