### ISSUE TITLE
Missing example in Docs for update-device-cellular-sims

### ISSUE THREAD

**Issue by bitboy85** [meraki/dashboard-api-python#205]
Hi,

The meraki python template is missing the param for the updated settings.
https://developer.cisco.com/meraki/api-latest/#!update-device-cellular-sims

**Comment by TKIPisalegacycipher** [comment]
Thank you for reporting this, @bitboy85. I was able to confirm this is the result of a bug with the spec for this endpoint, where the request body is not marked required, and thus none of the attributes are generated.

We intentionally exclude optional elements from the code snippets for the sake of simplicity and ease of learning, so we should not change the snippet generator to compensate for this bug in the spec.

To fix this, I've opened a bug with the appropriate team. To increase visibility of this issue with the appropriate team, you may optionally report the issue to support, mentioning case MG-2663 and requesting the fix. It always helps to hear the customer voice on these issues. 

Once that issue is fixed, the subsequent API docs update will include the updated example. Thanks again for noticing and reporting this, but since this is not an issue with the library, I will close this ticket.
