### ISSUE TITLE
Functions missing

### ISSUE THREAD

**Issue by gaurav1746** [meraki/dashboard-api-python#91]
Please add functions for content filtering and Intrusion prevention

**Comment by shiyuechengineer** [comment]
For which endpoints specifically, and v1 or v0?
If v1 on [this endpoint](https://developer.cisco.com/docs/meraki-api-v1/#!get-network-content-filtering) (as an example), then this is an issue we're aware of with the OpenAPI spec's tags for this operation being set incorrectly (categorized into "networks" instead of "appliance"), and will be fixed shortly.

**Comment by shiyuechengineer** [comment]
Fixed
